services:
  db:
    image: pgvector/pgvector:pg16
    container_name: mini-cdc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_cdc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini_cdc"]
      interval: 3s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: mini-cdc-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/2181'"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: mini-cdc-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092" # host에서 접근할 때
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # 내부/외부 리스너 둘 다 설정
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  api:
    build: .
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./schema.sql:/app/schema.sql
    container_name: mini-cdc-api
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@db:5432/mini_cdc"
      KAFKA_BOOTSTRAP: "kafka:9092"
      KAFKA_TOPIC: "product-events"
      JWT_SECRET_KEY: "dev-secret"
      JWT_ALGORITHM: "HS256"
      JWT_EXPIRE_MINUTES: "60"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "gpt-4o-mini"
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_REDIRECT_URL: ${SLACK_REDIRECT_URL}
      WEB_BASE_URL: ${WEB_BASE_URL}
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      --reload
      --reload-dir /app/app
      --reload-exclude ".venv/*"
      --reload-exclude "frontend/*"
      --reload-exclude "frontend/node_modules/*"
      --reload-exclude "**/__pycache__/*"
      --reload-exclude "**/*.pyc"
    restart: unless-stopped

  relay:
    build: .
    volumes:
      - ./app:/app/app
    container_name: mini-cdc-relay
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@db:5432/mini_cdc"
      KAFKA_BOOTSTRAP: "kafka:9092"
      KAFKA_TOPIC: "product-events"
      KAFKA_DLQ_TOPIC: "product-events-dlq"
      RELAY_MAX_RETRY: "5"
      RELAY_BATCH_SIZE: "200"
      RELAY_POLL_INTERVAL_SEC: "0.5"
    command: ["python", "-m", "relay.main"]
    restart: unless-stopped

  consumer:
    build: .
    volumes:
      - ./app:/app/app
      - ./consumer:/app/consumer
    container_name: mini-cdc-consumer
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@db:5432/mini_cdc"
      KAFKA_BOOTSTRAP: "kafka:9092"
      KAFKA_TOPIC: "product-events"
      CONSUMER_GROUP: "mini-cdc-consumer-v2"
    command: ["python", "-m", "consumer.main"]
    restart: unless-stopped

volumes:
  pgdata: